"""initial schema

Revision ID: 4e487e0d680c
Revises: 
Create Date: 2026-08-14 18:11:13.594624
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import callytics.db.models


revision = '4e487e0d680c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('destination', sa.String(length=16), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=False),
    sa.Column('external_audience_id', sa.String(length=120), nullable=True),
    sa.Column('last_synced_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('field_definitions',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('data_type', sa.String(length=24), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('legacy_schema_name', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lead_sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_high_intent', sa.Boolean(), nullable=False),
    sa.Column('is_bulk', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('lead_stages',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('is_revenue', sa.Boolean(), nullable=False),
    sa.Column('is_nurture', sa.Boolean(), nullable=False),
    sa.Column('is_artefact', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_group', sa.String(length=48), nullable=False),
    sa.Column('processed_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'consumer_group')
    )
    op.create_index('idx_pe_age', 'processed_events', ['processed_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_campaign', sa.String(length=190), nullable=True),
    sa.Column('source_medium', sa.String(length=80), nullable=True),
    sa.Column('source_referrer', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('do_not_sms', sa.Boolean(), nullable=False),
    sa.Column('do_not_email', sa.Boolean(), nullable=False),
    sa.Column('do_not_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('consent_source', sa.String(length=80), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_band', sa.String(length=8), nullable=False),
    sa.Column('first_touch_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('call_attempts', sa.Integer(), nullable=False),
    sa.Column('connected_calls', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('merged_into', sa.Uuid(), nullable=True),
    sa.Column('captured_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source'], ['lead_sources.name'], ),
    sa.ForeignKeyConstraint(['stage'], ['lead_stages.name'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_email', 'leads', ['email'], unique=False)
    op.create_index('idx_leads_last_activity', 'leads', ['last_activity_at'], unique=False)
    op.create_index('idx_leads_owner_stage', 'leads', ['owner_id', 'stage'], unique=False)
    op.create_index('idx_leads_phone', 'leads', ['phone'], unique=False)
    op.create_index('idx_leads_score', 'leads', ['score'], unique=False)
    op.create_index('idx_leads_source_captured', 'leads', ['source', 'captured_at'], unique=False)
    op.create_index('idx_leads_stage_updated', 'leads', ['stage', 'updated_at'], unique=False)
    op.create_index('idx_leads_team_stage', 'leads', ['team_id', 'stage'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('shared_with_team_id', sa.Uuid(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_view_owner_name')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('occurred_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=190), nullable=True),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('idx_activity_actor_time', 'activities', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('idx_activity_lead_time', 'activities', ['lead_id', 'occurred_at'], unique=False)
    op.create_index('idx_activity_type_time', 'activities', ['type', 'occurred_at'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('starts_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=190), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'starts_at', name='uq_appointment_slot')
    )
    op.create_index('idx_appointment_host_time', 'appointments', ['host_id', 'starts_at'], unique=False)
    op.create_index('idx_appointment_lead', 'appointments', ['lead_id'], unique=False)
    op.create_table('engagement_profiles',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('windows', sa.JSON(), nullable=False),
    sa.Column('preferred_channel', sa.String(length=20), nullable=True),
    sa.Column('responsiveness', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('sufficient_data', sa.Boolean(), nullable=False),
    sa.Column('computed_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('lead_identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('phone', 'email', name='identifier_kind'), nullable=False),
    sa.Column('value', sa.String(length=190), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_identifier_kind_value')
    )
    op.create_index('idx_identifier_lead', 'lead_identifiers', ['lead_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=190), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_recipient_read', 'notifications', ['recipient_id', 'read_at'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('proposed', sa.JSON(), nullable=False),
    sa.Column('current', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', 'auto_applied', name='proposal_status'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=190), nullable=True),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('decided_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('idx_proposal_lead_status', 'proposals', ['lead_id', 'status'], unique=False)
    op.create_index('idx_proposal_status_created', 'proposals', ['status', 'created_at'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=8), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('computed_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_lead_time', 'score_snapshots', ['lead_id', 'computed_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('due_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'completed', 'cancelled', 'overdue', name='task_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('completed_at', callytics.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('watchers', sa.JSON(), nullable=False),
    sa.Column('created_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assignee_due', 'tasks', ['assignee_id', 'status', 'due_at'], unique=False)
    op.create_index('idx_task_lead', 'tasks', ['lead_id'], unique=False)
    op.create_table('call_intelligence',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('agent_key', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('points_to_remember', sa.JSON(), nullable=False),
    sa.Column('objections', sa.JSON(), nullable=False),
    sa.Column('hooks', sa.JSON(), nullable=False),
    sa.Column('promised_actions', sa.JSON(), nullable=False),
    sa.Column('suggested_next_steps', sa.JSON(), nullable=False),
    sa.Column('detected_program', sa.String(length=120), nullable=True),
    sa.Column('call_type', sa.String(length=24), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('compliance_flags', sa.JSON(), nullable=False),
    sa.Column('recording_uri', sa.String(length=500), nullable=True),
    sa.Column('model_tag', sa.String(length=80), nullable=True),
    sa.Column('received_at', callytics.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('idx_ci_lead_time', 'call_intelligence', ['lead_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ci_lead_time', table_name='call_intelligence')
    op.drop_table('call_intelligence')
    op.drop_index('idx_task_lead', table_name='tasks')
    op.drop_index('idx_task_assignee_due', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_score_lead_time', table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index('idx_proposal_status_created', table_name='proposals')
    op.drop_index('idx_proposal_lead_status', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('idx_notif_recipient_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_identifier_lead', table_name='lead_identifiers')
    op.drop_table('lead_identifiers')
    op.drop_table('engagement_profiles')
    op.drop_index('idx_appointment_lead', table_name='appointments')
    op.drop_index('idx_appointment_host_time', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('idx_activity_type_time', table_name='activities')
    op.drop_index('idx_activity_lead_time', table_name='activities')
    op.drop_index('idx_activity_actor_time', table_name='activities')
    op.drop_table('activities')
    op.drop_table('team_members')
    op.drop_table('saved_views')
    op.drop_index('idx_leads_team_stage', table_name='leads')
    op.drop_index('idx_leads_stage_updated', table_name='leads')
    op.drop_index('idx_leads_source_captured', table_name='leads')
    op.drop_index('idx_leads_score', table_name='leads')
    op.drop_index('idx_leads_phone', table_name='leads')
    op.drop_index('idx_leads_owner_stage', table_name='leads')
    op.drop_index('idx_leads_last_activity', table_name='leads')
    op.drop_index('idx_leads_email', table_name='leads')
    op.drop_table('leads')
    op.drop_table('teams')
    op.drop_index('idx_audit_target', table_name='audit_log')
    op.drop_index('idx_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('idx_pe_age', table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_table('lead_stages')
    op.drop_table('lead_sources')
    op.drop_table('field_definitions')
    op.drop_table('audience_segments')
    # ### end Alembic commands ###
